# PRODUCTION
version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
  client:
    build:
      context: ./my-app3
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true